import React, { useEffect } from "react";
import './ContactUs.css'

const ContactUs = () => {
  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])
  return (
    <>
      <div className="contact-us">
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Numquam quidem iure velit esse. Qui amet eos voluptas ex autem quis perferendis, cumque maxime officia neque fugit repellat quos asperiores enim. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Est quisquam, eum provident eaque maxime ea veritatis! Provident eum molestias cupiditate, accusamus dolore iste fugit rem delectus doloremque deleniti tempora quo, totam esse maxime quisquam? Amet, natus, incidunt porro, reprehenderit quam obcaecati accusantium modi sint sunt eveniet placeat explicabo veritatis maxime pariatur? Consectetur, beatae mollitia ex accusamus aspernatur vitae libero in labore alias doloremque ut porro, autem illum. Quasi perferendis placeat autem iusto possimus consectetur deserunt tempore reprehenderit recusandae nisi. Velit accusamus, suscipit dolores commodi omnis aspernatur vel dolorum obcaecati quo non eos, ipsa beatae? Dolorum ut est natus similique quisquam molestias consequuntur vitae cumque aspernatur, magni libero sapiente assumenda? Sapiente, natus laborum molestiae culpa eius eos! Rem minus placeat, eaque asperiores, laboriosam accusamus doloremque aspernatur rerum voluptate sit, magnam hic laborum illo minima recusandae ex enim adipisci repellendus vitae odio. Nesciunt maiores qui iusto blanditiis molestiae minima ad tempora, debitis quisquam, quaerat, id doloribus laudantium. Necessitatibus asperiores aspernatur minima facilis! Blanditiis commodi repellendus omnis. Maiores doloremque culpa hic modi delectus adipisci qui illum magni aperiam dolorem rem quisquam numquam sequi cupiditate necessitatibus, molestias repellendus alias! Dolor necessitatibus autem, explicabo voluptatem delectus quae quaerat ullam nulla optio, alias cumque ut odit molestiae deserunt, enim laborum eum nostrum totam non ratione! Itaque ex quidem doloremque labore consequuntur at, accusantium nisi error perspiciatis dolores quis, sint, culpa consectetur nihil sit neque perferendis iure repellat. Eaque consequuntur, asperiores aspernatur laborum maiores tenetur ipsum, aliquam quam doloribus tempore dolore distinctio commodi perferendis? Quaerat voluptatibus explicabo odio iste corporis voluptate accusamus laudantium incidunt in! Soluta reiciendis quas cumque ratione eveniet sapiente quae. Quibusdam laudantium quasi non quisquam placeat vero enim ea, fuga quod vitae aut inventore ut atque dolores iusto distinctio eum modi mollitia neque consequatur consequuntur dolorum? Sint, magni expedita totam a ex fuga labore quas est voluptates dol
        ore officia, harum numquam minus saepe inventore porro. Quidem necessitatibus saepe repellendus deleniti enim vel itaque similique, perferendis atque quos! Cupiditate maiores earum culpa sapiente ipsa. Facilis nisi molestiae nihil maxime nostrum earum, est non explicabo, nam sequi aspernatur quibusdam, rerum alias reiciendis sunt? Porro nam eos doloribus labore quo quidem dolorum maxime natus. Accusantium explicabo excepturi eos sit eum aspernatur ipsa quibusdam dignissimos vel. Alias omnis facilis architecto voluptas error expedita ipsa voluptatum iure eligendi quasi, dicta consequatur laboriosam sint possimus quas ducimus quidem ipsam, deserunt neque doloremque suscipit cumque ex! Ut inventore repellat magnam! Ad tempora aut harum doloremque eveniet deleniti velit qui facere recusandae neque. Assumenda ipsam nam illo saepe quia possimus a qui amet. Iste similique animi quisquam assumenda illo ea ipsum doloribus vitae reprehenderit? Expedita ratione corporis placeat similique nesciunt doloribus cum dolorem est natus voluptatum. Officia minus magni maiores quas natus deserunt eum, possimus accusamus dolorem neque quae. Quod voluptate quae dolor, delectus aliquam error quo, deserunt laboriosam dolorem accusamus dicta laborum perferendis fuga corporis inventore itaque assumenda eaque ut suscipit accusantium? Ex magnam quas quisquam, non at reprehenderit ab qui dignissimos quis possimus. Beatae rem nihil, ut deserunt alias enim?
        <iframe src="https://www.google.com/maps/embed?pb=!1m23!1m12!1m3!1d98660.62308504428!2d77.28056139906623!3d23.224982380862567!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e6!4m5!1s0x3bc2e8215c673489%3A0x8d027e9931682392!2sDochaki%20Designs%2C%20Ratibad%2C%20Bhopal%2C%20Madhya%20Pradesh!3m2!1d23.177640999999998!2d77.3167406!4m0!5e0!3m2!1sen!2sin!4v1739881009870!5m2!1sen!2sin"></iframe>
      </div>
    </>
  )
}

export default ContactUs;